-- 5 tabelle del modello dati

create table if not exists campaigns (
  id                   bigint generated by default as identity primary key,
  name                 text not null,
  ac_list_match        text not null,
  twilio_template_sid  text not null,
  template_variables   jsonb not null default '[]'::jsonb,
  active               boolean not null default true,
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now()
);

create table if not exists leads (
  id              bigint generated by default as identity primary key,
  phone_e164      text not null unique,
  first_name      text,
  last_name       text,
  email           text,
  ac_contact_id   text,
  created_at      timestamptz not null default now()
);

create table if not exists conversations (
  id              bigint generated by default as identity primary key,
  lead_id         bigint not null references leads(id) on delete cascade,
  campaign_id     bigint references campaigns(id) on delete set null,
  last_message_at timestamptz not null default now(),
  last_inbound_at timestamptz,
  unread_count    int not null default 0,
  created_at      timestamptz not null default now(),
  unique(lead_id)
);

create table if not exists messages (
  id                bigint generated by default as identity primary key,
  conversation_id   bigint not null references conversations(id) on delete cascade,
  direction         text not null check (direction in ('in','out')),
  body              text not null,
  twilio_sid        text unique,
  twilio_status     text,
  twilio_error_code int,
  template_sid      text,
  template_vars     jsonb,
  is_template       boolean not null default false,
  read_at           timestamptz,
  created_at        timestamptz not null default now()
);

create table if not exists event_log (
  id         bigint generated by default as identity primary key,
  type       text not null,
  payload    jsonb,
  message    text,
  level      text not null default 'info' check (level in ('info','warn','error')),
  created_at timestamptz not null default now()
);

-- Trigger per updated_at su campaigns
create or replace function set_updated_at() returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger campaigns_set_updated_at
  before update on campaigns
  for each row execute function set_updated_at();
